# Generated by Django 5.2.7 on 2025-10-20 15:47

import django.db.models.deletion
import products.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='granted_permissions',
            field=models.ManyToManyField(blank=True, help_text='As "chaves" que este módulo adiciona aos papéis de administrador do assinante.', to='auth.permission', verbose_name='Permissões Concedidas'),
        ),
        migrations.AddField(
            model_name='product',
            name='suggested_modules',
            field=models.ManyToManyField(blank=True, help_text='Outros módulos que podem ser oferecidos a quem assina este.', to='products.product', verbose_name='Módulos Sugeridos'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=products.models.product_image_directory_path, verbose_name='Arquivo de Imagem')),
                ('alt_text', models.CharField(blank=True, help_text='Descrição da imagem para acessibilidade.', max_length=255, verbose_name='Texto Alternativo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro.', verbose_name='Ordem de Exibição')),
                ('is_main', models.BooleanField(default=False, help_text='Marque para destacar esta como a imagem principal do produto.', verbose_name='É a Imagem Principal?')),
                ('code', models.CharField(blank=True, help_text='Um código para uso do frontend (ex: "slider", "banner_full").', max_length=50, verbose_name='Código de Uso')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Produto (Módulo)')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens do Produto',
                'ordering': ['order'],
            },
        ),
    ]
