# Generated by Django 5.2.7 on 2025-10-20 00:27

import accounts.storages
import accounts.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome e sobrenome do usuário.', max_length=100, verbose_name='Nome Completo')),
                ('nickname', models.CharField(blank=True, help_text='Apelido ou primeiro nome.', max_length=100, null=True, verbose_name='Apelido')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Feminino')], max_length=10, null=True, verbose_name='Gênero')),
                ('cpf', models.CharField(help_text='CPF, apenas números.', max_length=11, unique=True, validators=[accounts.validators.validate_cpf], verbose_name='CPF')),
                ('date_birth', models.DateField(blank=True, help_text='Formato AAAA-MM-DD.', null=True, verbose_name='Data de Nascimento')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=accounts.storages.user_directory_path, verbose_name='Foto de Perfil')),
                ('email', models.EmailField(help_text='Utilizado para login e comunicação.', max_length=254, unique=True, verbose_name='E-mail')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='E-mail Verificado em')),
                ('whatsapp', models.CharField(db_index=True, help_text='Formato internacional E.164 (ex: +5538999998888).', max_length=20, unique=True, verbose_name='WhatsApp (E.164)')),
                ('whatsapp_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Whatsapp verificado em')),
                ('is_staff', models.BooleanField(default=False, help_text='Designa se o usuário pode fazer login no site de administração.', verbose_name='Membro da Equipe')),
                ('is_active', models.BooleanField(default=False, help_text='Designa se este usuário deve ser tratado como ativo.', verbose_name='Ativo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'auth_user',
                'ordering': ['-created_at'],
            },
        ),
    ]
