# Generated by Django 5.2.7 on 2025-10-20 00:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DzaionUsageProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Interruptor geral para ativar ou desativar o acesso do contratante à IA.', verbose_name='Contrato Ativo')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='O limite de gastos. Nulo significa ilimitado.', max_digits=10, null=True, verbose_name='Limite de Crédito (R$)')),
            ],
            options={
                'verbose_name': 'Perfil de Uso da IA',
                'verbose_name_plural': 'Perfis de Uso da IA',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, help_text='O preço exato que o inquilino concordou em pagar. Imutável.', max_digits=10, verbose_name='Preço (Snapshot)')),
                ('billing_cycle_details', models.JSONField(help_text='Cópia dos detalhes do ciclo de cobrança (ex: {"period": "MONTHLY", "discount": 10}).', verbose_name='Detalhes do Ciclo (Snapshot)')),
                ('features_snapshot', models.JSONField(help_text='A lista exata de features contratadas no momento da aquisição.', verbose_name='Funcionalidades (Snapshot)')),
                ('status', models.CharField(choices=[('TRIAL', 'Em Teste'), ('ACTIVE', 'Ativa'), ('PENDING', 'Pendente'), ('CANCELED', 'Cancelada'), ('INCOMPLETE', 'Incompleta')], default='INCOMPLETE', max_length=15, verbose_name='Status do Contrato')),
                ('start_date', models.DateField(verbose_name='Início da Vigência')),
                ('end_date', models.DateField(blank=True, help_text='Preenchido apenas para assinaturas canceladas.', null=True, verbose_name='Fim da Vigência')),
                ('next_billing_date', models.DateField(verbose_name='Próxima Cobrança')),
                ('gateway_subscription_id', models.CharField(blank=True, help_text='O identificador da assinatura no gateway de pagamento.', max_length=255, null=True, unique=True, verbose_name='ID da Assinatura no Gateway')),
            ],
            options={
                'verbose_name': 'Assinatura de Módulo',
                'verbose_name_plural': 'Assinaturas de Módulos',
                'ordering': ['-created_at'],
            },
        ),
    ]
