# Generated by Django 5.2.7 on 2025-10-20 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitlements', '0001_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dzaionusageprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dzaion_usage_profile', to='tenants.tenant', verbose_name='Inquilino (Contratante)'),
        ),
        migrations.AddField(
            model_name='dzaionusageprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dzaion_usage_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário (Contratante)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(help_text='Aponta para o plano que originou a assinatura (histórico).', on_delete=django.db.models.deletion.PROTECT, to='products.productplan', verbose_name='Plano de Referência'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant', verbose_name='Assinante (Inquilino)'),
        ),
        migrations.AddConstraint(
            model_name='dzaionusageprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tenant__isnull', False), ('user__isnull', True)), models.Q(('tenant__isnull', True), ('user__isnull', False)), _connector='OR'), name='exclusive_owner_for_usage_profile'),
        ),
        migrations.AddConstraint(
            model_name='dzaionusageprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant',), name='unique_tenant_usage_profile'),
        ),
        migrations.AddConstraint(
            model_name='dzaionusageprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_user_usage_profile'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'TRIAL'])), fields=('tenant', 'plan'), name='unique_active_subscription_per_tenant_plan'),
        ),
    ]
