# Generated by Django 5.2.7 on 2025-10-20 00:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelContacts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome do Canal')),
                ('icon', models.CharField(blank=True, help_text="Classe do ícone para o frontend (ex: 'fab fa-whatsapp').", max_length=50, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Canal de Contato',
                'verbose_name_plural': 'Canais de Contato',
                'ordering': ['name'],
            },
        ),
    ]
