# Generated by Django 5.2.7 on 2025-10-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Canal')),
                ('icon', models.CharField(max_length=50, verbose_name='Ícone')),
            ],
        ),
    ]
