# Generated by Django 5.2.7 on 2025-10-22 04:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome Legível')),
                ('identifier', models.CharField(max_length=100, unique=True, verbose_name='Identificador de API')),
                ('usage_mode', models.CharField(choices=[('REAL_TIME', 'Tempo Real'), ('BATCH', 'Em Lote (Batch)')], max_length=15, verbose_name='Modo de Operação')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Modelo de IA',
                'verbose_name_plural': 'Modelos de IA',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIThoughtProcess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING_EXECUTION', 'Pendente de Execução'), ('PENDING_USER_RESPONSE', 'Aguardando Usuário'), ('PROCESSING', 'Em Processamento'), ('FINISHED', 'Finalizado'), ('FAILED', 'Falhou')], default='PENDING_EXECUTION', max_length=25, verbose_name='Progresso da Tarefa')),
                ('expires_at', models.DateTimeField(verbose_name='Prazo de Validade')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
            ],
            options={
                'verbose_name': 'Processo de Pensamento da IA',
                'verbose_name_plural': 'Processos de Pensamento da IA',
                'ordering': ['-expires_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('FINISHED', 'Finalizada'), ('ARCHIVED', 'Arquivada')], default='ACTIVE', max_length=15, verbose_name='Status da Conversa')),
            ],
            options={
                'verbose_name': 'Conversa com IA',
                'verbose_name_plural': 'Conversas com IA',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DzaionAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Ação')),
                ('verb_code', models.CharField(max_length=100, unique=True, verbose_name='Verbo (Código Interno)')),
                ('cost_bearer', models.CharField(choices=[('SYSTEM', 'Sistema (Gratuito)'), ('CONTRACTOR', 'Contratante (Pago)')], default='CONTRACTOR', max_length=15, verbose_name='Responsável pelo Custo')),
                ('default_expiration_seconds', models.PositiveIntegerField(default=3600, verbose_name='Prazo Padrão (segundos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('instructions', models.TextField(blank=True, verbose_name='Instruções para a IA')),
                ('parameters_schema', models.JSONField(blank=True, default=dict, verbose_name='Schema de Parâmetros (Tool Calling)')),
            ],
            options={
                'verbose_name': 'Ação da IA (Verbo)',
                'verbose_name_plural': 'Ações da IA (Verbos)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('INBOUND', 'Entrada (Usuário -> IA)'), ('OUTBOUND', 'Saída (IA -> Usuário)')], max_length=10, verbose_name='Direção')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('SENT', 'Enviada'), ('DELIVERED', 'Entregue'), ('READ', 'Lida'), ('FAILED', 'Falhou')], default='SENT', max_length=10, verbose_name='Status da Entrega')),
            ],
            options={
                'verbose_name': 'Mensagem de Conversa',
                'verbose_name_plural': 'Mensagens de Conversa',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_tokens', models.PositiveIntegerField(verbose_name='Tokens de Entrada')),
                ('output_tokens', models.PositiveIntegerField(verbose_name='Tokens de Saída')),
                ('is_billed', models.BooleanField(db_index=True, default=False, verbose_name='Faturado?')),
            ],
            options={
                'verbose_name': 'Log de Uso de Tokens',
                'verbose_name_plural': 'Logs de Uso de Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
