# Generated by Django 5.2.7 on 2025-10-22 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dzaion', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aithoughtprocess',
            name='tenant_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Contexto do Inquilino'),
        ),
        migrations.AddField(
            model_name='aithoughtprocess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thought_processes', to=settings.AUTH_USER_MODEL, verbose_name='Interlocutor'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tenants.tenant', verbose_name='Inquilino (Proprietário)'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário (Proprietário)'),
        ),
        migrations.AddField(
            model_name='aithoughtprocess',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='thought_process', to='dzaion.conversation', verbose_name='Conversa Associada'),
        ),
        migrations.AddField(
            model_name='dzaionaction',
            name='default_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dzaion.aimodel', verbose_name='Modelo de IA Padrão'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='initial_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dzaion.dzaionaction', verbose_name='Ação Inicial'),
        ),
        migrations.AddField(
            model_name='aithoughtprocess',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dzaion.dzaionaction', verbose_name='Ação (Missão)'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dzaion.conversation', verbose_name='Conversa'),
        ),
        migrations.AddField(
            model_name='tokenusagelog',
            name='ai_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dzaion.aimodel', verbose_name='Modelo de IA Utilizado'),
        ),
        migrations.AddField(
            model_name='tokenusagelog',
            name='dzaion_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dzaion.dzaionaction', verbose_name='Ação (Motivo)'),
        ),
        migrations.AddField(
            model_name='tokenusagelog',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dzaion.message', verbose_name='Mensagem de Origem'),
        ),
        migrations.AddField(
            model_name='tokenusagelog',
            name='payer_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage_logs', to='tenants.tenant', verbose_name='Inquilino (Pagador)'),
        ),
        migrations.AddField(
            model_name='tokenusagelog',
            name='payer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário (Pagador)'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tenant__isnull', False), ('user__isnull', True)), models.Q(('tenant__isnull', True), ('user__isnull', False)), _connector='OR'), name='exclusive_owner_for_conversation'),
        ),
        migrations.AddConstraint(
            model_name='tokenusagelog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payer_tenant__isnull', False), ('payer_user__isnull', True)), models.Q(('payer_tenant__isnull', True), ('payer_user__isnull', False)), _connector='OR'), name='exclusive_payer_for_token_log'),
        ),
    ]
