# Generated by Django 5.2.7 on 2025-10-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzaion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='identifier',
            field=models.CharField(help_text='O nome técnico exato do modelo para as chamadas de API (ex: gpt-4o).', max_length=100, unique=True, verbose_name='Identificador de API'),
        ),
        migrations.AlterField(
            model_name='dzaionaction',
            name='default_expiration_seconds',
            field=models.PositiveIntegerField(default=3600, help_text='Tempo para expirar um AIThoughtProcess. 0 significa que nunca expira.', verbose_name='Prazo Padrão (segundos)'),
        ),
        migrations.AlterField(
            model_name='dzaionaction',
            name='instructions',
            field=models.TextField(blank=True, help_text='O prompt de sistema (instrução) específico para esta ação.', verbose_name='Instruções para a IA'),
        ),
        migrations.AlterField(
            model_name='dzaionaction',
            name='parameters_schema',
            field=models.JSONField(blank=True, default=dict, help_text='A definição em JSON Schema dos parâmetros que esta ação requer.', verbose_name='Schema de Parâmetros (Tool Calling)'),
        ),
        migrations.AlterField(
            model_name='dzaionaction',
            name='verb_code',
            field=models.CharField(help_text='O código interno usado pelo sistema (ex: activate_account).', max_length=100, unique=True, verbose_name='Verbo (Código Interno)'),
        ),
    ]
