# Generated by Django 5.2.7 on 2025-10-20 00:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('OPEN', 'Aberta'), ('PAID', 'Paga'), ('CANCELED', 'Cancelada'), ('UNCOLLECTIBLE', 'Inadimplente')], default='DRAFT', max_length=15, verbose_name='Status da Fatura')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('billing_details_snapshot', models.JSONField(blank=True, help_text='Snapshot dos dados do Tenant no momento da emissão.', null=True, verbose_name='Dados de Faturamento (Snapshot)')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Descrição do Item')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Item')),
                ('source_id', models.UUIDField(help_text='O ID do objeto que gerou esta cobrança (ex: uma Assinatura).', verbose_name='ID da Origem da Cobrança')),
                ('source_type', models.CharField(help_text='Identifica o tipo do objeto de origem (ex: "subscription").', max_length=100, verbose_name='Tipo da Origem')),
            ],
            options={
                'verbose_name': 'Item da Fatura',
                'verbose_name_plural': 'Itens da Fatura',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valores positivos para créditos (entradas) e negativos para débitos (saídas).', max_digits=12, verbose_name='Valor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou')], default='PENDING', max_length=15, verbose_name='Status da Transação')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Transação no Gateway')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='Resposta do Gateway')),
                ('processed_at', models.DateTimeField(verbose_name='Processada em')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome Legível')),
                ('code', models.CharField(help_text='Ex: INVOICE_PAYMENT, IA_USAGE_DEBIT', max_length=50, unique=True, verbose_name='Código Interno')),
                ('is_debit', models.BooleanField(default=True, help_text='Define se a operação representa uma saída (débito) de fundos.', verbose_name='É um Débito?')),
            ],
            options={
                'verbose_name': 'Tipo de Transação',
                'verbose_name_plural': 'Tipos de Transações',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Carteira de Créditos',
                'verbose_name_plural': 'Carteiras de Créditos',
            },
        ),
    ]
