# Generated by Django 5.2.7 on 2025-10-20 00:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dzaion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='O nome legível para o papel (ex: "Administrador", "Membro").', max_length=100, verbose_name='Nome do Papel')),
                ('is_admin_role', models.BooleanField(default=False, help_text='Se marcado, concede acesso administrativo total no contexto do seu Tenant.', verbose_name='É um Papel de Administrador?')),
                ('dzaion_actions', models.ManyToManyField(blank=True, help_text='Ações específicas da Dzaion IA que este papel pode executar.', to='dzaion.dzaionaction', verbose_name='Ações da IA')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissões do Django que este papel concede.', to='auth.permission', verbose_name='Permissões do Sistema')),
            ],
            options={
                'verbose_name': 'Papel (Role)',
                'verbose_name_plural': 'Papéis (Roles)',
                'ordering': ['tenant__name', 'name'],
            },
        ),
    ]
