# Generated by Django 5.2.7 on 2025-10-20 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guards', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='O Tenant ao qual este papel pertence. Se nulo, é um papel global.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Inquilino (Tenant)'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_role_name'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('name',), name='unique_global_role_name'),
        ),
    ]
