# Generated by Django 5.2.7 on 2025-10-18 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_object_id', models.UUIDField(db_index=True)),
                ('verb', models.CharField(help_text='O verbo que descreve a ação (ex: criou, pagou, comentou em).', max_length=255, verbose_name='Verbo')),
                ('target_object_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('FINANCIAL', 'Financeiro'), ('SOCIAL', 'Social'), ('ADMINISTRATIVE', 'Administrativo'), ('SERVICE', 'Serviço')], db_index=True, help_text='A categoria do evento, para facilitar a filtragem.', max_length=20, verbose_name='Tipo de Evento')),
                ('data_snapshot', models.JSONField(blank=True, help_text='Dados relevantes do evento no momento em que ele ocorreu.', null=True, verbose_name='Registro Imutável (Snapshot)')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='O momento exato em que o evento original ocorreu no módulo de origem.', verbose_name='Timestamp do Evento')),
                ('is_read', models.BooleanField(default=False, help_text='True se o usuário já visualizou a atividade no feed.', verbose_name='Status de Leitura')),
                ('priority', models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Média'), ('LOW', 'Baixa')], default='LOW', help_text='A urgência do evento, usada para destaques e pela IA.', max_length=10, verbose_name='Prioridade')),
                ('actor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_activities', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_activities', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='O usuário a quem esta atividade pertence e para quem ela será exibida.', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Dono do Feed')),
            ],
            options={
                'verbose_name': 'Atividade do Usuário',
                'verbose_name_plural': 'Atividades dos Usuários',
                'ordering': ['-timestamp'],
            },
        ),
    ]
