# Generated by Django 5.2.7 on 2025-10-11 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(max_length=255, verbose_name='Verbo de Ação direciona a informação dentro do módulo')),
                ('target_object_id', models.UUIDField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link para a página expecífica')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('priority', models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Média'), ('LOW', 'Baixa')], default='MEDIUM', max_length=10, verbose_name='Prioridade')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuário', to=settings.AUTH_USER_MODEL, verbose_name='activities')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
